feat: add upload avatar sb-49
ZenBit-Tech/sunny-bunnies_fe pull request #22
Opened 2024-06-19 19:10 UTC by Vfivew

### **General**
- [ ] Assigned myself to the PR
- [ ] Assigned the appropriate labels to the PR
- [ ] Assigned the appropriate reviewers to the PR
- [ ] Updated the documentation
- [ ] Performed a self-review of my code
- [ ] Types for input and output parameters
- [ ] Don't have "any" on my code
- [ ] Used the try/catch pattern for error handling
- [ ] Don't have magic numbers
- [ ] Compare only with constants not with strings
- [ ] No ternary operator inside the ternary operator
- [ ] Don't have commented code
- [ ] no links in the code, env links should be in env file
- [ ] Used camelCase for variables and functions
- [ ] Date and time formats are on the constants
- [ ] Functions are public only if it's used outside the class
- [ ] No hardcoded values
- [ ] covered by tests
- [ ] Check your commit messages meet
### Frontend
- [ ] Components and business logic are separated
- [ ] Colors, Font Size, and Font Name is on the theme or in the
- [ ] No text in the components, use i18n approach
- [ ] No inline styles
- [ ] Imports are absolute
- [ ] Attach a screenshot if PR has visual changes.

2024-06-20 11:08 UTC, ValentinaTenus requested changes

2024-06-20 11:08 UTC, ValentinaTenus commented on src/pages/profile-board/validation/constants.ts
>  	cardNumberRequired: "Card number is required",
consts are written in different styles

2024-06-21 11:59 UTC, ValentinaTenus approved these changes

2024-06-21 12:36 UTC, likeri29 approved these changes

2024-06-21 12:58 UTC, merged